/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-background": "var(--on-background)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "on-error-container": "var(--on-error-container)",
        "secondary-container": "var(--secondary-container)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "secondary-fixed": "var(--secondary-fixed)",
        "primary-fixed": "var(--primary-fixed)",
        "on-primary": "var(--on-primary)",
        "surface-bright": "var(--surface-bright)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "surface-container-low": "var(--surface-container-low)",
        surface: "var(--surface)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        background: "var(--background)",
        "surface-dim": "var(--surface-dim)",
        tertiary: "var(--tertiary)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "surface-container-highest": "var(--surface-container-highest)",
        "tertiary-container": "var(--tertiary-container)",
        "surface-container-high": "var(--surface-container-high)",
        "inverse-surface": "var(--inverse-surface)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-secondary": "var(--on-secondary)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "primary-container": "var(--primary-container)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "surface-tint": "var(--surface-tint)",
        "on-primary-container": "var(--on-primary-container)",
        "surface-variant": "var(--surface-variant)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-tertiary": "var(--on-tertiary)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        secondary: "var(--secondary)",
        "surface-container": "var(--surface-container)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        error: "var(--error)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-error": "var(--on-error)",
        "on-surface": "var(--on-surface)",
        outline: "var(--outline)",
        primary: "var(--primary)",
        "inverse-primary": "var(--inverse-primary)",
        "error-container": "var(--error-container)",
        "outline-variant": "var(--outline-variant)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        margin: "0.5rem",
        gutter: "0.75rem",
        "space-sm": "0.375rem",
        "space-xl": "1rem",
        "margin-desktop": "0.75rem",
        "gutter-desktop": "1rem",
        "space-2xl": "1.5rem",
        "space-2xs": "0.125rem",
        "space-md": "0.5rem",
        "space-xs": "0.25rem",
        "space-lg": "0.75rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      boxShadow: {
        nav: "0 1px 8px rgba(0,0,0,0.04)",
        card: "0 1px 4px rgba(0,0,0,0.03)",
        overlay:
          "0 4px 12px -2px rgba(15, 23, 42, 0.08), 0 2px 4px -1px rgba(15, 23, 42, 0.04)",
        modal:
          "0 20px 25px -5px rgba(15, 23, 42, 0.12), 0 8px 10px -6px rgba(15, 23, 42, 0.06)",
      },
      fontSize: {
        "label-sm": [
          "0.6875rem",
          { lineHeight: "0.875rem", letterSpacing: "0.04em", fontWeight: "500" },
        ],
        "code-md": ["0.8125rem", { lineHeight: "1.375rem", fontWeight: "400" }],
        "headline-lg": [
          "1.75rem",
          { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-md": [
          "1.25rem",
          { lineHeight: "1.75rem", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        "code-sm": ["0.75rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "body-md": ["0.875rem", { lineHeight: "1.375rem", fontWeight: "400" }],
        "headline-sm": [
          "1rem",
          { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "code-lg": ["0.9375rem", { lineHeight: "1.625rem", fontWeight: "400" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "body-lg": ["0.9375rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "label-md": [
          "0.75rem",
          { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "500" },
        ],
      },
    },
  },
  plugins: [],
};
